### PR TITLE
feat(web-ui): rework ui

### PR DESCRIPTION
**Pull request by AugustinMauroy**
# WARING it's not finish I open pre to show how it's look now.

But it's need a lot of cleaning. Also I'm not expert in `svelte` so if I'm missing any practical bones, let me know.

### CODE REVIEW

**Comment by aduh95** [comment]
Before this change:

````
vite v4.4.4 building for production...
✓ 41 modules transformed.
dist/index.html                  2.06 kB │ gzip: 0.78 kB
dist/assets/index-4a129365.css   0.64 kB │ gzip: 0.27 kB
dist/assets/index-b890d69c.js   21.32 kB │ gzip: 8.41 kB
✓ built in 497ms
````

After this change:

````
vite v4.4.4 building for production...
✓ 48 modules transformed.
dist/index.html                  0.75 kB │ gzip:  0.44 kB
dist/assets/index-9d6f33c7.css  15.12 kB │ gzip:  3.02 kB
dist/assets/index-3d5ac82e.js   29.36 kB │ gzip: 10.66 kB
✓ built in 1.02s
````

It's a significant increase, not sure it's worth it.

**Comment by AugustinMauroy** [comment]
> It's a significant increase, not sure it's worth it.

I couldn't agree more. You can do it using classic CSS. But increase js is about making reusable components.

**Comment by AugustinMauroy** [comment]
and what do you thinks about design ?

**Comment by aduh95** [comment]
> and what do you thinks about design ?

I don't really have any opinion, I'm happy to not to design decisions because I feel out of my depth.



> But increase js is about making reusable components.

It seems to me that we are increasing complexity for very little benefit, Caritat UI does not aim to become more than it currently is, I kinda doubt we would ever benefit from the reusability.
My preference would be to keep it as minimal a runtime as possible, so it's easier to maintain and more accessible to folks with bad internet connection.

**Comment by AugustinMauroy** [comment]
I will try to simplify such à possible

**Pull request closed without merging**
